### ISSUE TITLE
help with a seperate project

### ISSUE THREAD

**Issue by 24098762409875odfhasodf** [TheZookeeper1/DisqusBot#1]
I'm making something to generate session IDs and was wondering if you could help. (currently just generating strings with format similar to session IDs and checking if it's valid, probably will take me a year to get a single one.)

**Comment by TheZookeeper1** [comment]
Hi, I had a similiar idea, but no luck since its an enormous amount of possible IDs. How could I help you?

**Comment by 24098762409875odfhasodf** [comment]
I've played around with some python and session IDs and I've understood it a little better. We could probably make a script to mass generate accounts (since session IDs do expire even if its in like a half year). I'm able to provide [captchamonster.cloud](https://capmonster.cloud/en/) funding if needed (for the captchas).

Do you have a messaging platform account? (Preferably Guilded/Discord)

**Comment by 24098762409875odfhasodf** [comment]
I did some stuff with the recaptcha_v2_solver and it works (added your rotating proxies too). We can now sign-up infinitely with enough emails. Time for more testing.

**Comment by 24098762409875odfhasodf** [comment]
I got a generator working with 10 proxies.
Currently takes a minute to generate 1, but the rate can be increased to a max of idk with around 100 proxies? idk

**Comment by TheZookeeper1** [comment]
Sounds good so far. I'm busy with a lot of other things right now. I will look into it and come back to you. Feel free to share your progress though.

**Comment by 24098762409875odfhasodf** [comment]
Alright!
Do you have a messaging platform? (preferably discord/guilded)

**Comment by 24098762409875odfhasodf** [comment]
> https://www.guilded.gg/i/24AY3Rnk

You should probably invalidate that link now by going into server settings. Anyways, I'll close this now.
